---
title: "P5 Spatial data analysis: introduction to raster processing (part-4)"
author: "Joao Goncalves"
date: "25 November 2017"
output:
  html_document: 
    self_contained: no
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = "img/")
knitr::opts_chunk$set(fig.width = 5, fig.height = 4.5, dpi = 80)

```

### Background 

-------------------------------------------------------------------------------------------------------

In the fourth part of this tutorial series on spatial data analysis using the `raster` package, 
we will explore more functionalities, this time related to time-series analysis. We will use an 
Enhanced Vegetation Index ([EVI](https://en.wikipedia.org/wiki/Enhanced_vegetation_index)) 5-year 
time-series (from year 2012 to 2016) from Terra/MODIS satellite/sensor platform for The Peneda-Geres 
National Park (PGNP, in NW Portugal) to develop some examples. 

This data corresponds to MODIS's __MOD13Q1 data product__ version-006 ([+info here](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mod13q1_v006)) which has 250m 
of spatial resolution and, 16-days of temporal resolution (more precisely, the product is generated by 
maximum daily value composites for each 16-day period). This means that each year has a total of 23 observations. 
These data was downloaded from the [EarthData](https://search.earthdata.nasa.gov/search) platform and later 
assembled and reprojected to WGS 1984 - UTM 29N Coordinate Reference System (CRS) using MRTWeb tool (sorry 
but these pre-processing steps are outside the scope of this tutorial `r emo::ji("grin")`).

In this post we will also introduce `RasterBrick`s, a multi-layer raster object typically created from a multi-layer 
(or multi-band) file although they can also exist entirely in memory. These objects are similar to `RasterStack`s, but 
processing time should be shorter when using a `RasterBrick` (irrespective if values are on disk or in memory). 
However these objects are less flexible as they can only point to a single file, while `RasterStacks` can 
point to multiple different files.

For more information on raster data processing see [here](http://r-exercises.com/tags/raster-data), as well as the [tutorial part-1](https://www.r-exercises.com/2017/11/29/spatial-data-analysis-introduction-to-raster-processing-part-1), [tutorial part-2](https://www.r-exercises.com/2017/12/13/spatial-data-analysis-introduction-to-raster-processing-part-2), and, [tutorial part-3](https://www.r-exercises.com/2018/01/10/spatial-data-analysis-introduction-to-raster-processing-part-3), of this 
series.


### Background 

-------------------------------------------------------------------------------------------------------

```{r P5_download_data}

## Create a folder named data-raw inside the working directory to place downloaded data
if(!dir.exists("./data-raw")) dir.create("./data-raw")

## If you run into download problems try changing: method = "wget"
download.file("https://raw.githubusercontent.com/joaofgoncalves/R_exercises_raster_tutorial/master/data/srtm_pnpg.zip", "./data-raw/srtm_pnpg.zip", method = "auto")

## Uncompress the zip file
unzip("./data-raw/srtm_pnpg.zip", exdir = "./data-raw")



```

Creating the raster brick 

```{r P5_create_raster_brick}

library(raster)




```













